// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingProject.Database.Context;

#nullable disable

namespace WeddingProject.Migrations
{
    [DbContext(typeof(SqlServerDbContext))]
    [Migration("20240127173213_updated")]
    partial class updated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeddingProject.Entities.AboutPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutDescHome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutDescHome2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutDescHome3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutDescHomeImagePath1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutDescHomeImagePath2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutDescHomeImagePath3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutDescHomeImagePath4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutOurMission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutOurMissionDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutSecondTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OurMissionImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service1Count")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service1Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service2Count")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service2Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service3Count")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service3Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service4Count")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service4Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboutPages");
                });

            modelBuilder.Entity("WeddingProject.Entities.ContactPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactFace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInsta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactSecondTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactWp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContctTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactPages");
                });

            modelBuilder.Entity("WeddingProject.Entities.HomePage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HomePage1ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePage2ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePage3ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePage4ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePageDesc1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePageDesc2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePageDescTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OurHistoryDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OurHistoryStick1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OurHistoryStick2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OurHistoryStick3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OurHistoryStick4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OurHistoryStick5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OurHistoryStick6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OurHistoryTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service1Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service1Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service2Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service3Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service3Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service4Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service4Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slider1ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slider1Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slider2ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slider2Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slider3ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slider3Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomePages");
                });
#pragma warning restore 612, 618
        }
    }
}
